displayName: taxifare_20220327_041143
studySpec:
  metrics:
  - metricId:  # TODO: Your code goes here
    goal: MINIMIZE
  parameters:
  - parameterId: lr
    # TODO: Your code goes here
  - parameterId: nbuckets
    # TODO: Your code goes here
  - parameterId: batch_size
    # TODO: Your code goes here
  algorithm: ALGORITHM_UNSPECIFIED # results in Bayesian optimization
trialJobSpec:
  baseOutputDirectory:
    outputUriPrefix: gs:///taxifare_20220327_041143
  workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    pythonPackageSpec:
      args:
      - --train_data_path=gs:///taxifare/data/taxi-train*
      - --eval_data_path=gs:///taxifare/data/taxi-valid*
      - --batch_size=15
      - --num_examples_to_train_on=100
      - --num_evals=10
      - --nbuckets=10
      - --lr=0.001
      - --nnsize=32 8
      executorImageUri: us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-8:latest
      packageUris:
      - gs:///taxifare/taxifare_trainer-0.1.tar.gz
      pythonModule: trainer.task
    replicaCount: 1
